### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by CmetankaJDD** [Hadi-koubeissi/ManageGift#48]
Dear bot developers, please help solve the following error: TypeError: Cannot read properties of undefined (reading 'enabled') at Object.run (C:\Users\Den\Desktop\бот\reg\ManageGift-master\commands\Info\configuration.js:16:49) at module.exports (C:\Users\Den\Desktop\бот\reg\ManageGift-master\events\discord\interactionCreate.js:81:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) This error occurs with every command and it cannot determine 'enabled'.

**Comment by CmetankaJDD** [comment]
TypeError: Cannot read properties of undefined (reading 'enabled') occurs after each bot command is applied.

**Comment by Hadi-koubeissi** [comment]
I stope supporting the open source version of this bot and if you need help you must be a patreon subscriber
